### ISSUE TITLE
Software Manager is not themed

### ISSUE THREAD

**Issue by greenlaw110** [Elbullazul/Windows-10#18]
![image](https://cloud.githubusercontent.com/assets/216930/13216836/84dcceac-d9b2-11e5-86d4-0e6b4fb256da.png)

**Comment by Elbullazul** [comment]
It happens when the theme is placed in ~/.themes. Try out the Transfo Pack installer wich installs the files as a global theme (root has also access to the theme) wich will make the SC look like this : 
![capture du 2016-02-22 08 10 08](https://cloud.githubusercontent.com/assets/15310985/13219103/d40f2b9a-d93b-11e5-8c2c-5da14b9ab6e5.png)

**Comment by greenlaw110** [comment]
Yes it makes sense as software manager is launched as root user. After I moved the theme to /user/share/themes it looks been stylyzed.

However it still looks ugly in comparing to other built-in tools like

The driver manager (also run in root privilege):
![image](https://cloud.githubusercontent.com/assets/216930/13269638/e90284b4-dadc-11e5-8860-c0487ca481ac.png)

Power statistics:
![image](https://cloud.githubusercontent.com/assets/216930/13269649/fae57b82-dadc-11e5-9f08-1d06ecc1ec2f.png)

Backup tool (also run in root privilege):
![image](https://cloud.githubusercontent.com/assets/216930/13269656/08bd0964-dadd-11e5-8ea0-3cd5709d19f9.png)

**Comment by Elbullazul** [comment]
Well,  I figured that the look of the software center doesn't depend on css theming. It's built in the code of the app and it isn't customizable.  Sorry.

**Comment by greenlaw110** [comment]
Understood, I think we should submit an issue to Mint. That's something they need to improve
