### ISSUE TITLE
Suggestion: Separate Issues/Bug Tracking from Conversations

### ISSUE THREAD

**Issue by MichaelTunnell** [Elbullazul/Windows-10#61]
I think this project is garnering clutter in the GitHub issues when they should be utilized for only development or perhaps support purposes.

GitHub Issues are better for bug reports, development discussions, feature requests, etc.

Instead of using GitHub for conversations (like general chat) perhaps this project should look into setting up a Gitter room. - https://gitter.im/

Gitter is free for open source projects, like GitHub, so it should work nicely. One of the best features of GitHub is they have an IRC bridge so people who want to use IRC instead of their official clients can do so. :)

@Elbullazul

**Comment by feren** [comment]
@MichaelTunnell Fact: We did use that, but for some reason, Cinnamoner of Elbullazul decided to go back here

**Comment by MichaelTunnell** [comment]
Hmm that's interesting. I wonder what the reason behind that was.

**Comment by Elbullazul** [comment]
tried to use gitter, but it didn't work out

also, one of the collabs can't use gitter well (he emails back to github), I don't know if gitter can do that too. Maybe the IRC thing can help this out

Cinnamoner went back here, I think because he's more comfortable with the structure of the communication (more forum-ish vs chat-room style)

but, for the sake of the project, I can try to convince everyone to move to gitter

**Comment by Elbullazul** [comment]
@feren @cinnamoner  @bluedxca93 from now on, please use gitter for conversation purposes

here's the link: https://gitter.im/Elbullazul/Windows-10

**All non-issue related threads will be closed and I will warn the user to where to post his/her message**

this is not meant to harm anyone, just, like @MichaelTunnell says, to avoid messing things even more than what they are now

**Comment by cinnamoner** [comment]
@Elbullazul Okay.

**Comment by feren** [comment]
Now locking the thread...

**Comment by cinnamoner** [comment]
@feren here too, the same itch. Just do what you see fit.
